title: Ruby Development With Docker
description: Learn how to develop Ruby by leveraging docker.
template:
  repo: ruby-development-with-docker-template
  name: ruby-development-with-docker
before:
  - type: createPullRequest
    title: Welcome!
    body: 01_pull_body.md
    branch: add-dockerfile
steps:
  - title: Create your Ruby Docker container
    description: Create a docker container with Ruby installed.
    event: pull_request.synchronize
    link: '{{ repoUrl }}/pull/1'
    actions:
      - type: mergePullRequest
        pullRequest: Welcome!
      - type: respond
        issue: Welcome!
        body: 01_pull_request_merged.md
