title: Ruby Development With Docker
description: Learn how to develop Ruby by leveraging docker.

template:
  repo: ruby-development-with-docker-template
  name: ruby-development-with-docker

before:
  - type: createPullRequest
    title: Welcome!
    body: 01_pull_body.md
    head: add-ruby-to-dockerfile
    action_id: first_pr

steps:
  # introduce user to creating a container, adding Ruby by using a parent container
  - title: Create your Ruby Docker container
    description: Create a docker container with Ruby installed.
    link: '{{ repoUrl }}/pull/1'
    event: check_suite
    actions:
      - type: gate
        gates:
          # if this check fails...it's just in-progress?
          - left: "%payload.check_suite.status%"
            operator: ===
            right: "completed"
          - type: gate
            left: "%payload.check_suite.conclusion%"
            operator: ===
            right: "success"
            else:
              - type: respond
                with: 01_did_not_change_to_ruby_base.md

      # ok wt-actual fuck
      - type: respond
        with: debug
        data:
          debug: "%payload%"
          message: "CHECK SUITE PAYLOAD CAME IN"

      # steps to do after validating that user properly updated dockerfile
      - type: createPullRequest
        title: Building Up The Ruby Environment
        body: 02_pull_body.md
        head: adding-gemfile
        action_id: second_pr
      - type: respond
        issue: Welcome!
        with: 01_pull_request_dockerfile_updated.md
        data:
          dependenciesPRLink: '{{ actions.second_pr.data.html_url }}'
      - type: mergePullRequest
        pullRequest: Welcome!
      - type: deleteBranch
        branch: add-ruby-to-dockerfile

  # introduce user to the concept of installing dependencies, persisting them via containers
  - title: Adding Dependencies into Your Docker Container
    description: Create your Gemfile, installing dependencies into your container.
    event: pull_request.synchronize
    link: '{{ repoUrl }}/pull/2'
    actions:
      - type: createPullRequest
        title: Writing Code!
        body: 03_pull_body.md
        head: adding-code
        action_id: third_pr
      - type: respond
        issue: Building Up The Ruby Environment
        with: 02_dependencies_added.md
        data:
          finalPRLink: '{{ actions.third_pr.data.html_url }}'
      - type: mergePullRequest
        pullRequest: Building Up The Ruby Environment
      - type: deleteBranch
        branch: adding-gemfile

  # finally write some code, teach user how to run tests in the container locally
  - title: Writing Code!
    description: Start writing code, learn how to develop within your container.
    event: pull_request.synchronize
    link: '{{ repoUrl }}/pull/3'
    actions:
      - type: respond
        issue: Writing Code!
        with: 03_congrats.md
      - type: mergePullRequest
        pullRequest: Writing Code!
      - type: deleteBranch
        branch: adding-code
